/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

object App:

  import ChecksumAccumulator.calculate
  def main(args: Array[String]): Unit = {
    println(greeting())

    val q = Person("sally", 49)

    for arg <- args do
      println(arg + ": " + calculate(arg))
  }

  def greeting(): String = "Hello, world!"

