/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.scalatest.funsuite.AnyFunSuite

class AppSuite extends AnyFunSuite {
  test("App has a greeting") {
    assert(App.greeting() != null)
  }
}
